# =========================================
# SERVICE INFO
# =========================================
spring.application.name=yowyob-enchere-backend-reactive
server.port=8031
spring.webflux.base-path=/api

# =========================================
# CASSANDRA (REACTIVE)
# =========================================
spring.cassandra.keyspace-name=enchereyowyob
# Remplacez par les points de contact de votre cluster Cassandra
spring.cassandra.contact-points=3.94.159.36
spring.cassandra.port=8761
# Le nom du datacenter local, crucial pour le driver
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
# Credentials si nécessaire
# spring.data.cassandra.username=${CASSANDRA_USER}
# spring.data.cassandra.password=${CASSANDRA_PASS}
spring.cassandra.request.timeout=10s

# =========================================
# SECURITY & JWT
# =========================================
# Votre clé secrète pour valider les tokens JWT
app.jwt.secret-key=${JWT_SECRET:faceb782375b50f9d24e043beeca80fae093c934cbf0ade576f4b36258de6b44}


# =========================================
# UPLOAD FILES
# =========================================
# Chemin sur le serveur où les fichiers sont stockés
app.upload.path=${UPLOAD_PATH:uploads/}
# URL de base pour accéder aux fichiers uploadés publiquement
app.upload.base-url=${UPLOAD_BASE_URL:http://157.90.26.3:8031/api/uploads/}

# =========================================
# DOCUMENTATION API (OpenAPI/Swagger)
# =========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# =========================================
# SPRING BOOT CONFIG
# =========================================
spring.main.allow-bean-definition-overriding=true

server.url=http://157.90.26.3:8031